/**
 * Generates a Markdown report string from a Report document.
 * @param {Object} report - The Mongoose report document.
 * @returns {string} - The formatted Markdown string.
 */
const generateMarkdown = (report) => {
  const lines = [];

  lines.push(`# OSINT Intelligence Report`);
  lines.push(``);
  lines.push(`**Target:** ${report.targetName}`);
  lines.push(`**Risk Level:** ${report.riskLevel}`);
  lines.push(`**Generated:** ${new Date(report.createdAt).toLocaleString()}`);
  lines.push(``);
  lines.push(`---`);
  lines.push(``);

  if (report.summary) {
    lines.push(`## Summary`);
    lines.push(``);
    lines.push(report.summary);
    lines.push(``);
    lines.push(`---`);
    lines.push(``);
  }

  lines.push(`## Intelligence Vectors (${report.results.length} Sources)`);
  lines.push(``);

  report.results.forEach((vector, idx) => {
    lines.push(`### ${idx + 1}. ${vector.source}`);
    lines.push(``);
    lines.push(`- **Category:** ${vector.category}`);
    lines.push(`- **Confidence:** ${vector.confidenceScore || "N/A"}`);
    lines.push(
      `- **Timestamp:** ${new Date(vector.timestamp).toLocaleString()}`,
    );

    if (vector.sourceUrl) {
      lines.push(`- **Source URL:** ${vector.sourceUrl}`);
    }

    lines.push(``);
    lines.push(`#### Raw Data`);
    lines.push(``);
    lines.push("```json");
    lines.push(JSON.stringify(vector.data, null, 2));
    lines.push("```");
    lines.push(``);
  });

  lines.push(`---`);
  lines.push(`*Report generated by OSINT Intelligence Platform*`);

  return lines.join("\n");
};

export default generateMarkdown;
